language: node_js
node_js: 8
cache:
  yarn: true
  directories:
  - node_modules
  - "${NVM_PATH}_modules"
install:
- yarn
- cd functions && yarn && cd ..
script:
- yarn lint
- echo "Building..."
- if [ "$TRAVIS_BRANCH" == "develop" ]; then yarn build; fi
- if [ "$TRAVIS_BRANCH" == "hoverboard-v2" ]; then yarn build:prod; fi
before_deploy:
- echo "Deploying!"
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: develop
  project: devfest-5388e
  token:
    secure: "JV//C9oq7LpkDHQWFAfMoUPiRe/pIM9BwJ/8OYOzulFcCld3zvN4HO1Z3xGcRcTCnNrI3AOgv4KqDZ5NgG9G9M0wyz0vgp9ynaRz2B3SIddqY+LV5xB68yN7vt5sRQngVEVhbyoo1sQBrm0hXvlGbMUiD+a1u8jMk+el8N0eHJwkzuopOthLaBp6tUjWbPjPYMHdeRS9l2JODfXe69C/NC6FZsUUDQP/AMmli1qzFQCQtzpovwtvP1sYSiVO4ZBDgKOEGq7leNBfVx1soXIBFSy5IBO/PQ7JtqTT8jG/dGo0x3o/1gQTheikidkB4KjAn+FPIpY7vLMgJRJvfvYy5eRlYtuKVgES7oNZXqjm5Y5ztsZMSSpvGJFZxYQtCg/sCJGzOzI/CYnUsLHkA/JatCNFyRij7jXhCRHl9Au4zvW/IL4FsAiup+XZJKJ3Bibh0Ml9/oJuznDQvtWYK0coNicJCdeTv+VPU4nzTXupCEtVp3+50Lv4nl0s7ZbePqMgBTMc4dq9Xbw3MOgHqTjh5ezqlzJbZ/weUrC0pi0VpbpDsYN+StVmf1av7P6cVOBmwUhTtwHhNhcZgQDc5u8uBbj6zvw8mmA0nPyhujc4Rs+1w1UBlj19Xm52fiNTpCatGzoD6EjzG0JUXMxGRPG8fQ0UU3q20PwCd2fUWGhC+QQ="
- provider: firebase
  skip_cleanup: true
  on:
    branch: hoverboard-v2
  project: books2go-56df4
# env:
#   global:
#     secure: Zbwn3BZpSIWjhMB4c+vewmfj9yoy63RaqFKJe1gGMP2o3wEsJlJBBmzEOtAeexuhYEXYiHheHB50H+CnGY5e/NnwkB9MZAAGibKfuzrNOT8jFIi61rJaGDHs4q013wQhD2Lb69D8da9XeoES1Eh7kYZoJN+m2zQs4QObzm9shAXfH80GEDrWbXGful6CIN+79aKQCJz8mpnxLbRT0W6fcmMi40ixlz3WynJvZNlA0PVJoiuZf0q9Dyg0D5Zg90Hr0H60gOrbetF7Ub0aQqcvlvMp4bkNgWnZMQyvNHYyfWDqeyIymN0bTxGcv6YUGMSW8I2ROQRy+X4EIv69toINB2z52jtprsUSSv6foRENOXjeBXBhcgV2fAp5uWr5DofAyGAjx7bPzcwL66KHQUiENKXyOmzXekTuwnFRA9nd4Lt/dPwg3vfFLpHBStOQj1biUJ5XWErHiYJdf64OI0FdGJesgU0uDg+mL0nu8SmquX0BXUSwsPC61/dA/g8uPvlMMHBpBPfvtLPCZwfKs1+VNQKmrnP3ujzQRkAPoYbKikW3V1XIKHM38e43x35dbvFoEvl8k1XP3A72zxOt+eiJiBhp9VHppSCHzmGSsCK2P+EAe1lVJISZbaYVbXoCEera6za+oTkuzHoacwzkhp9eiT2awHPb0i1k8pi/ad1li2I=
