language: node_js
node_js: 8
cache:
  yarn: true
  directories:
  - node_modules
  - "${NVM_PATH}_modules"
install:
- yarn
- cd functions && yarn && cd ..
script:
- yarn lint
- echo "Building..."
- if [ "$TRAVIS_BRANCH" == "develop" ]; then yarn build; fi
- if [ "$TRAVIS_BRANCH" == "hoverboard-v2" ]; then yarn build:prod; fi
before_deploy:
- echo "Deploying!"
deploy:
# - provider: firebase
#   skip_cleanup: true
#   on:
#     branch: master
#   project: hoverboard-master
#   token:
#     secure: fQOOIF4mkqH438Dawy2v27Qw7UsVizfJ1ZIeTno2sGfq9an8mZk13YWBuYJcOc1hSnEEp3G7/pkBcwykCj1CYpoOS+wMxpVbOQw6ogMGFD8rv+208Ddt1VJw/uUuFdf4k07+eRGokykCsCmcv2J+5wnLw34CKzXYTxLpL6JrxGzkuAcKIRNNda13yxJfYXz7HtQiNo3aMYnv2MCffNnSaR+OJ9Cl0JGYDCg3zuJIqrq7CFJqnUXE5TsO0VGCLY46rLvICY6inNlgZvA4RWi6Yf4rs2swzgC7HKbcIipjptlCRpPdRigLKoxhv6HZUIpkVgDu10Jq6OWU5gj4VpNYYd+c+E4F23nvm+3BEToUuEGURZ9Ins1SSHr3d+WxneQ+jreHCGrEBhKkLknbPQuOQF3khtk9CHu+07fBafBCLt4dGC6oQu+QwTdn+JQ/rYxWAUq8yJjrTsKevgXAVyMqDTU1Fy7FH5QP7HRyI71C6Q7Ij3cVwrFrVXNGzg2h2q8qTX2Yn6Ph9NJUpS+QmVsymblh38zwlyThZ1T4XudYM5iZTzNKKVqCmR9upl8nSLMEez1ukhBETJCslb2nFXJI3k7dsFA5cGO51sbYB44bxIXJwZkQ0s9p8XBNsU9gI2hX6UvE5+tephbohd6YGHmfc+qaJkLpcYKjRbhFsysf60k=
- provider: firebase
  skip_cleanup: true
  on:
    branch: develop
  project: devfest-5388e
  token:
    secure: "bmsrGc9898ygZj0Uikkm8ALEQOoa+8w8uAfzUBHcn+iQejRexeKLfApd5pmwDsb2wpHsfTitu/ntzJMwfRFlny60ovQ0isYneDZj1cTlr2ObGarRtlJTpxj63LPMIbTyWF5hSxogU4RahQfrY6NiBZbdO66rf98Zc+vFchSukKqGSE5ZgVTdFnPtDkqKLlrtKmd/STXPmRXKzaKNstEeczIM6kvvx3MLWM7dDFOVuzW+JT8rn1xu3WWvigCykDc0hKKuBPAPWGwaVqCCA8GSPDGocMqfa1loLbMTuyJ65Y3BsHdXr+wsen8hKayQpddjbi8i2GIehf5JuGNMD5QwMZUmeo+ziNxuTWuAMBB37q/NqOm52UftJgINcBiKTHMUvOlxvq1IzfSyylrktmNitfiEY4mXtNcg8eyIMg7MRx55FixeZokJ7dVY5eyYFYNOEqVv9NBzcU20xxD8ziRLAhSlY6H8cVITixlZXU+ub4v+mcVEwvnsVm1geKXk+nu+f52TVJ/lvMlmau78rMkCGpA6+wl8P5VRlZLX5rZ/OcslIxA8cxVPKXRPi8CPuKohcXvI/aavF7DuJ0PqrnXieoA0LnWQMKtYnmnCamCjRHbs92aWwmJDN4Iz/iGGkZgj2rdRaQ0rB6wh9Awj0TXebTonEKyl/W7sMh4umLekR8k="
- provider: firebase
  skip_cleanup: true
  on:
    branch: hoverboard-v2
  project: books2go-56df4